#!/bin/bash

source ~/.cache/wal/chunkwmcolors

NFOCUS=$(echo $FOCUS | sed 's/#//')
NPRESE=$(echo $PRESE | sed 's/#//')

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1
chunkc core::unload tiling.so
chunkc core::unload ffm.so
chunkc core::unload border.so

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          1
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.15
chunkc set window_use_cgs_move 1

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp

chunkc set custom_bar_enabled            1
chunkc set custom_bar_all_monitors       1
chunkc set custom_bar_offset_top         20
chunkc set custom_bar_offset_bottom      20
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

chunkc set global_desktop_offset_top     20
chunkc set global_desktop_offset_bottom  20
chunkc set global_desktop_offset_left    20
chunkc set global_desktop_offset_right   20
chunkc set global_desktop_offset_gap     20

chunkc set desktop_padding_step_size     5.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_modifier                fn

chunkc set preselect_border_color        $NPRESE
chunkc set preselect_border_width        6
chunkc set preselect_border_radius       1

chunkc set focused_border_color          $NFOCUS
chunkc set focused_border_width          6
chunkc set focused_border_radius         1
chunkc set focused_border_skip_floating  1

chunkc tiling::rule --owner kitty --role AXWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner iTerm --role AXWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner Hyper --role AXWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner Keybase --role AXWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner \"System Preferences\" --state float
chunkc tiling::rule --owner Finder --name Copy --state tile &
chunkc tiling::rule --owner Console --state tile &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Übersicht --state float &
chunkc tiling::rule --owner Dashlane --state float &
chunkc tiling::rule --owner mpv --state tile &

#
# NOTE: the following are config variables for the chunkwm-ffm plugin.
#

chunkc set ffm_bypass_modifier           \"cmd shift\"
chunkc set ffm_standby_on_float 0

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load purify.so
chunkc core::load border.so

chunkwm --load-sa
