#!/bin/bash

source ~/.cache/wal/chunkwmcolors

NFOCUS=$(echo $FOCUS | sed 's/#//')
NPRESE=$(echo $PRESE | sed 's/#//')
WAL=$(cat ~/.cache/wal/wal)

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1
chunkc core::unload tiling.so
chunkc core::unload purify.so
chunkc core::unload blur.so

chunkc core::log_file /usr/local/var/log/chunkwm/chunkwm.err.log

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          1
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.75
chunkc set window_fade_duration          0.15
chunkc set window_use_cgs_move 0

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp

chunkc set custom_bar_enabled            1
chunkc set custom_bar_all_monitors       1
chunkc set custom_bar_offset_top         20
chunkc set custom_bar_offset_bottom      20
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

chunkc set global_desktop_offset_top     5
chunkc set global_desktop_offset_bottom  5
chunkc set global_desktop_offset_left    5
chunkc set global_desktop_offset_right   5
chunkc set global_desktop_offset_gap     5

chunkc set desktop_padding_step_size     5.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set mouse_modifier                fn


#
# NOTE: the following are config variables for the chunkwm-blur plugin.
#

chunkc set wallpaper $WAL
chunkc set wallpaper_blur 30.0


#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load tiling.so
chunkc core::load purify.so
chunkc core::load blur.so

chunkc tiling::rule --owner kitty --name zathura --state tile &
chunkc tiling::rule --owner kitty --name Launcher --state float &
chunkc tiling::rule --owner iTerm2 --name Preferences --state float &
chunkc tiling::rule --owner Hyper --role AXWindow --subrole AXDialog --state tile &
chunkc tiling::rule --owner Keybase --role AXWindow --subrole AXDialog --state tile &
chunkc tiling::rule --owner \"System Preferences\" --state float &
chunkc tiling::rule --owner Finder --name Copy --state tile &
chunkc tiling::rule --owner \"Archive Utility\" --state float &
chunkc tiling::rule --owner Console --state tile &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Übersicht --state float &
chunkc tiling::rule --owner snwe --state float &
chunkc tiling::rule --owner Dashlane --state float &
chunkc tiling::rule --owner mpv --state tile &

chunkwm --load-sa
